//! 参照検索・dead-code 判定の走査対象ファイル収集。
//!
//! `.gitignore` 尊重 + ディレクトリ名 / ネガティブ glob による除外 + 生成物
//! (minified / `@generated` マーカー / IDE ヘルパー) の除外を担う。

use anyhow::Result;
use std::path::Path;

use crate::language::LangId;

/// ignore クレートでファイルを収集する（.gitignore 対応）。
pub fn collect_files(dir: &Path, glob_pattern: Option<&str>) -> Result<Vec<std::path::PathBuf>> {
    collect_files_with_excludes(dir, glob_pattern, &[], &[])
}

/// ignore クレートでファイルを収集し、ディレクトリ名またはネガティブ glob で除外する。
///
/// - `excluded_dir_names`: 完全一致するパスセグメント (例: `vendor`, `node_modules`) を
///   含むファイルを除外。軽量な判定用。
/// - `excluded_globs`: `database/migrations/**` のような glob パターン (ワークスペース相対)。
///   内部で `!<pattern>` として `ignore::overrides` に追加し、パッケージパス内の特定サブ
///   ディレクトリだけをピンポイント除外する。
///
/// 両方が空であれば `collect_files(dir, glob)` と同じ挙動。`.gitignore` は常に尊重する。
pub fn collect_files_with_excludes(
    dir: &Path,
    glob_pattern: Option<&str>,
    excluded_dir_names: &[&str],
    excluded_globs: &[&str],
) -> Result<Vec<std::path::PathBuf>> {
    use ignore::WalkBuilder;

    let mut builder = WalkBuilder::new(dir);
    builder.hidden(true).git_ignore(true).git_global(true);

    // glob フィルタと除外 glob を同じ OverrideBuilder にまとめる。
    // ignore::overrides は「ポジティブパターンがある → その中だけ許可 / ネガティブ (`!`
    // 接頭辞) → 除外」なので、glob_pattern が None のときも `**/*` を足してから
    // `!excluded_globs...` を重ねることで「全体許可 + 指定分だけ除外」を実現する。
    if glob_pattern.is_some() || !excluded_globs.is_empty() {
        let mut ob = ignore::overrides::OverrideBuilder::new(dir);
        if let Some(pattern) = glob_pattern {
            ob.add(pattern)?;
        } else if !excluded_globs.is_empty() {
            ob.add("**/*")?;
        }
        for pat in excluded_globs {
            let negated = if pat.starts_with('!') {
                pat.to_string()
            } else {
                format!("!{pat}")
            };
            ob.add(&negated)?;
        }
        builder.overrides(ob.build()?);
    }

    let exclude_generated = !is_generated_exclusion_disabled();
    let mut files = Vec::new();
    for entry in builder.build() {
        let entry = entry?;
        if !entry.file_type().is_some_and(|ft| ft.is_file()) {
            continue;
        }
        let path = entry.into_path();
        if !excluded_dir_names.is_empty() {
            // root (`dir`) からの相対パスでセグメント判定する。`dir` が
            // `/private/tmp/test/myrepo` のように親パスに除外セグメント名
            // (例: `test`) を含むと、リポ内全ファイルが誤除外される false negative を防ぐ。
            let rel = path.strip_prefix(dir).unwrap_or(&path);
            if path_has_excluded_segment(rel, excluded_dir_names) {
                continue;
            }
        }
        // ベンダー / IDE 補助 / `@generated` マーカー付きファイルは
        // ノイズ源になるため refs / impact / dead-code から除外する。
        // 例: `vendor/`, `node_modules/`, `_ide_helper.php`, `*.min.js` 等。
        // `ASTRO_SIGHT_NO_GENERATED_EXCLUSION=1` で抑止可能。
        if exclude_generated && is_generated_file(&path) {
            continue;
        }
        // パース可能なファイルのみ対象
        if LangId::from_path(camino::Utf8Path::new(path.to_str().unwrap_or(""))).is_ok() {
            files.push(path);
        } else if path.extension().is_none() && detect_lang_from_shebang(&path).is_some() {
            // 拡張子なしの実行スクリプト (例: `bin/install`) は shebang から言語推定。
            // CLI ツール / ビルドスクリプトで shebang 命名は一般的なので、これを
            // collect_files から落とさない。
            files.push(path);
        }
    }

    Ok(files)
}

/// `ASTRO_SIGHT_NO_GENERATED_EXCLUSION=1` のときだけ generated ファイル除外を抑止する。
fn is_generated_exclusion_disabled() -> bool {
    std::env::var("ASTRO_SIGHT_NO_GENERATED_EXCLUSION")
        .ok()
        .filter(|v| !v.is_empty() && v != "0")
        .is_some()
}

/// IDE 補助 / minified / `@generated` マーカー付きのファイル単位 generated 判定。
///
/// **vendor/node_modules 等のディレクトリ単位の除外はこの関数では行わない**。
/// それらは dead-code の `--include-vendor` のような opt-in がある呼び出し側で
/// `excluded_dir_names` 経由で個別に制御される。
///
/// 以下のいずれかに該当する場合 true を返す:
/// - ファイル名が Laravel IDE Helper 系 (`_ide_helper.php`, `_ide_helper_*.php`, `_lighthouse_ide_helper.php`)
/// - ファイル名が minified / bundled (`*.min.js`, `*.min.css`, `*.bundle.js`)
/// - ファイル先頭 4KB に `@generated`, `DO NOT EDIT`, `Code generated by`,
///   `This file is auto-generated`, `automatically generated` のいずれかを含む
pub(crate) fn is_generated_file(path: &Path) -> bool {
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        if name.starts_with("_ide_helper") && name.ends_with(".php") {
            return true;
        }
        if name == "_lighthouse_ide_helper.php" {
            return true;
        }
        if name.ends_with(".min.js") || name.ends_with(".min.css") || name.ends_with(".bundle.js") {
            return true;
        }
    }
    has_generated_marker(path)
}

/// ファイル先頭 4KB に generated マーカーが含まれるかを判定する。
///
/// I/O コスト軽減のため最大 4KB のみ読む。マーカー文字列は UTF-8 妥当性を問わず
/// バイト列としてマッチさせる (memchr::memmem)。読めない場合は false を返す
/// (パーミッション欠落等で誤って除外しない)。
fn has_generated_marker(path: &Path) -> bool {
    use std::io::Read;
    let Ok(mut file) = std::fs::File::open(path) else {
        return false;
    };
    let mut buf = [0u8; 4096];
    let Ok(n) = file.read(&mut buf) else {
        return false;
    };
    let head = &buf[..n];
    memchr::memmem::find(head, b"@generated").is_some()
        || memchr::memmem::find(head, b"DO NOT EDIT").is_some()
        || memchr::memmem::find(head, b"Code generated by").is_some()
        || memchr::memmem::find(head, b"This file is auto-generated").is_some()
        || memchr::memmem::find(head, b"automatically generated").is_some()
}

/// 拡張子なしファイルの先頭 shebang 行から言語を判定する。
///
/// I/O コスト軽減のため最大 4KB だけ読み、最初の 2 byte が `#!` でなければ即時 None。
/// 実行ビット等は判定せず、shebang の有無だけで言語推定可能かを決める。
fn detect_lang_from_shebang(path: &Path) -> Option<LangId> {
    use std::io::Read;
    let mut file = std::fs::File::open(path).ok()?;
    let mut buf = [0u8; 4096];
    let n = file.read(&mut buf).ok()?;
    if n < 2 || &buf[..2] != b"#!" {
        return None;
    }
    let line_end = buf[..n].iter().position(|&b| b == b'\n').unwrap_or(n);
    let first_line = std::str::from_utf8(&buf[..line_end]).ok()?;
    LangId::from_shebang(first_line)
}

/// パスのいずれかの中間ディレクトリ名が除外対象と完全一致するかを判定する。
fn path_has_excluded_segment(path: &Path, excluded: &[&str]) -> bool {
    path.components().any(|c| match c.as_os_str().to_str() {
        Some(name) => excluded.contains(&name),
        None => false,
    })
}

/// workspace walk の結果 `files` に、diff 由来などの明示ファイルを canonical path で
/// 合流させる (workspace 外・解決不能・重複は除外)。hidden ディレクトリ配下でも候補に
/// なったファイル自身の参照を取りこぼさないための共通ヘルパー
/// (count 経路と member liveness 経路で走査集合を一致させる)。
pub fn merge_extra_files(
    files: &mut Vec<std::path::PathBuf>,
    canonical_dir: &Path,
    extra_files: &[std::path::PathBuf],
) {
    if extra_files.is_empty() {
        return;
    }
    let mut seen: std::collections::HashSet<std::path::PathBuf> = files.iter().cloned().collect();
    for extra in extra_files {
        let candidate = if extra.is_absolute() {
            extra.clone()
        } else {
            canonical_dir.join(extra)
        };
        let Ok(canonical) = std::fs::canonicalize(candidate) else {
            continue;
        };
        if canonical.starts_with(canonical_dir) && seen.insert(canonical.clone()) {
            files.push(canonical);
        }
    }
}
