[package]
name = "usage-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
simd-json = "0.17.3"
rayon = "1.12.0"
glob = "0.3.4"
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
comfy-table = "8.0.0"
serde_json = "1.0.151"
dirs = "6"

[profile.release]
lto = true
strip = true
