use super::*;

#[test]
fn is_generated_file_detects_laravel_ide_helper() {
    let path = Path::new("Laravel/www/_ide_helper.php");
    assert!(super::is_generated_file(path));
    let path = Path::new("Laravel/www/_ide_helper_models.php");
    assert!(super::is_generated_file(path));
    let path = Path::new("Laravel/www/_lighthouse_ide_helper.php");
    assert!(super::is_generated_file(path));
}

#[test]
fn is_generated_file_passes_vendor_dir() {
    // vendor/node_modules はここではなく呼び出し側 (dead-code の
    // --include-vendor opt-in 等) で制御するため、is_generated_file は通す。
    let path = Path::new("Laravel/www/vendor/composer/Foo.php");
    assert!(!super::is_generated_file(path));
    let path = Path::new("Angular/www/node_modules/lib/index.ts");
    assert!(!super::is_generated_file(path));
}

#[test]
fn is_generated_file_detects_minified_assets() {
    assert!(super::is_generated_file(Path::new("public/app.min.js")));
    assert!(super::is_generated_file(Path::new("public/app.min.css")));
    assert!(super::is_generated_file(Path::new("public/app.bundle.js")));
}

#[test]
fn is_generated_file_passes_normal_source() {
    // 通常のソースファイルは false
    let path = Path::new("src/app/services/log.service.ts");
    assert!(!super::is_generated_file(path));
    let path = Path::new("Laravel/www/app/Http/Controllers/UserController.php");
    assert!(!super::is_generated_file(path));
}

#[test]
fn is_generated_file_detects_at_generated_marker() {
    // ファイル先頭マーカー判定を確認
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("foo.php");
    std::fs::write(&path, "<?php\n// @generated by some-tool\nclass X {}\n").expect("write");
    assert!(super::is_generated_file(&path));

    let path2 = dir.path().join("bar.php");
    std::fs::write(&path2, "<?php\n// hand-written\nclass Y {}\n").expect("write");
    assert!(!super::is_generated_file(&path2));
}

#[test]
fn is_generated_file_detects_do_not_edit_marker() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("gen.go");
    std::fs::write(
        &path,
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n",
    )
    .expect("write");
    assert!(super::is_generated_file(&path));
}

#[test]
fn collect_files_handles_generated_exclusion() {
    // 並列テストで env を共有するため 1 つのテストに集約してシリアル化する。
    // (1) デフォルトで _ide_helper.php が除外される
    // (2) ASTRO_SIGHT_NO_GENERATED_EXCLUSION=1 で opt-out できる
    let prev = std::env::var("ASTRO_SIGHT_NO_GENERATED_EXCLUSION").ok();
    // 念のため事前に unset して default 動作を保証する
    // SAFETY: Rust 2024 Edition では set_var/remove_var は unsafe 扱い。
    // env を読む他テストは存在しない (検索済み) ため本テスト内のみ操作する。
    unsafe {
        std::env::remove_var("ASTRO_SIGHT_NO_GENERATED_EXCLUSION");
    }

    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(dir.path().join("_ide_helper.php"), "<?php class X {}\n").expect("write");
    std::fs::write(dir.path().join("real.php"), "<?php class Real {}\n").expect("write");

    // (1) default: _ide_helper.php は除外、real.php は含まれる
    let files = super::collect_files(dir.path(), None).expect("collect");
    let names: Vec<_> = files
        .iter()
        .filter_map(|p| p.file_name().and_then(|n| n.to_str()))
        .collect();
    let default_real = names.contains(&"real.php");
    let default_ide = names.contains(&"_ide_helper.php");

    // (2) opt-out: env="1" で _ide_helper.php も含まれる
    // SAFETY: Rust 2024 で unsafe。テスト終了時に restore する。
    unsafe {
        std::env::set_var("ASTRO_SIGHT_NO_GENERATED_EXCLUSION", "1");
    }
    let files = super::collect_files(dir.path(), None).expect("collect");
    let optout_ide = files
        .iter()
        .any(|p| p.file_name().and_then(|n| n.to_str()) == Some("_ide_helper.php"));

    // restore
    // SAFETY: テスト終了処理。
    unsafe {
        match prev {
            Some(v) => std::env::set_var("ASTRO_SIGHT_NO_GENERATED_EXCLUSION", v),
            None => std::env::remove_var("ASTRO_SIGHT_NO_GENERATED_EXCLUSION"),
        }
    }

    assert!(
        default_real,
        "通常ファイルは default で含まれるべき。got names: {names:?}"
    );
    assert!(
        !default_ide,
        "_ide_helper.php は default で除外されるべき。got names: {names:?}"
    );
    assert!(optout_ide, "opt-out 時は _ide_helper.php も含まれるべき");
}
