use super::*;

#[test]
fn is_generated_file_detects_laravel_ide_helper() {
    let path = Path::new("Laravel/www/_ide_helper.php");
    assert!(super::is_generated_file(path));
    let path = Path::new("Laravel/www/_ide_helper_models.php");
    assert!(super::is_generated_file(path));
    let path = Path::new("Laravel/www/_lighthouse_ide_helper.php");
    assert!(super::is_generated_file(path));
}

#[test]
fn is_generated_file_passes_vendor_dir() {
    // vendor/node_modules はここではなく呼び出し側 (dead-code の
    // --include-vendor opt-in 等) で制御するため、is_generated_file は通す。
    let path = Path::new("Laravel/www/vendor/composer/Foo.php");
    assert!(!super::is_generated_file(path));
    let path = Path::new("Angular/www/node_modules/lib/index.ts");
    assert!(!super::is_generated_file(path));
}

#[test]
fn is_generated_file_detects_minified_assets() {
    assert!(super::is_generated_file(Path::new("public/app.min.js")));
    assert!(super::is_generated_file(Path::new("public/app.min.css")));
    assert!(super::is_generated_file(Path::new("public/app.bundle.js")));
}

#[test]
fn is_generated_file_passes_normal_source() {
    // 通常のソースファイルは false
    let path = Path::new("src/app/services/log.service.ts");
    assert!(!super::is_generated_file(path));
    let path = Path::new("Laravel/www/app/Http/Controllers/UserController.php");
    assert!(!super::is_generated_file(path));
}

#[test]
fn is_generated_file_detects_at_generated_marker() {
    // ファイル先頭マーカー判定を確認
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("foo.php");
    std::fs::write(&path, "<?php\n// @generated by some-tool\nclass X {}\n").expect("write");
    assert!(super::is_generated_file(&path));

    let path2 = dir.path().join("bar.php");
    std::fs::write(&path2, "<?php\n// hand-written\nclass Y {}\n").expect("write");
    assert!(!super::is_generated_file(&path2));
}

#[test]
fn is_generated_file_detects_do_not_edit_marker() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("gen.go");
    std::fs::write(
        &path,
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n",
    )
    .expect("write");
    assert!(super::is_generated_file(&path));
}

#[test]
fn collect_files_handles_generated_exclusion() {
    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(dir.path().join("_ide_helper.php"), "<?php class X {}\n").expect("write");
    std::fs::write(dir.path().join("real.php"), "<?php class Real {}\n").expect("write");

    // Process-global な環境変数を unit test 内で変更すると、並列実行中の
    // generated scan と競合する。legacy env の opt-out は子プロセスを使う
    // integration test で検証し、ここでは default の純粋な挙動だけを固定する。
    let files = super::collect_files(dir.path(), None).expect("collect");
    let names: Vec<_> = files
        .iter()
        .filter_map(|p| p.file_name().and_then(|n| n.to_str()))
        .collect();

    assert!(
        names.contains(&"real.php"),
        "通常ファイルは default で含まれるべき。got names: {names:?}"
    );
    assert!(
        !names.contains(&"_ide_helper.php"),
        "_ide_helper.php は default で除外されるべき。got names: {names:?}"
    );
}

#[test]
fn collect_files_scan_reports_generated_and_honors_explicit_controls() {
    let dir = tempfile::tempdir().expect("tempdir");
    let generated = dir.path().join("generated.rb");
    let real = dir.path().join("real.rb");
    std::fs::write(&generated, "# @generated by a tool\ndef hidden_name; end\n")
        .expect("write generated");
    std::fs::write(&real, "def visible_name; end\n").expect("write real");

    let default_scan =
        super::collect_files_scan(dir.path(), None, super::FileScanOptions::default())
            .expect("default scan");
    assert_eq!(default_scan.files, vec![real.clone()]);
    let skipped = default_scan.skipped(dir.path()).expect("skip metadata");
    assert_eq!(skipped.generated, 1);
    assert_eq!(skipped.paths, vec!["generated.rb"]);
    assert!(!skipped.truncated);

    let included = super::collect_files_scan(
        dir.path(),
        None,
        super::FileScanOptions {
            include_generated: true,
        },
    )
    .expect("include generated scan");
    assert!(included.files.contains(&generated));
    assert!(included.skipped(dir.path()).is_none());

    let explicit = super::collect_files_scan(
        dir.path(),
        Some("**/generated.rb"),
        super::FileScanOptions::default(),
    )
    .expect("explicit glob scan");
    assert_eq!(explicit.files, vec![generated.clone()]);
    assert!(explicit.skipped(dir.path()).is_none());

    let broad = super::collect_files_scan(
        dir.path(),
        Some("**/*.rb"),
        super::FileScanOptions::default(),
    )
    .expect("broad glob scan");
    assert_eq!(broad.files, vec![real]);
    assert_eq!(
        broad.skipped(dir.path()).expect("broad skip").paths,
        vec!["generated.rb"]
    );
}
