//! コード生成ツールによる「自動生成ファイル」のマーカー検出。
//! `.gitattributes` の `linguist-generated` と独立に、ファイル先頭のコメントで
//! 生成物を宣言しているパターン (tree-sitter の `parser.c`、`protoc` の
//! `_pb.go` など) を捉える。dead-code / API 変更検出のノイズ抑制に使う。

use std::io::Read;
use std::path::Path;

/// ファイル先頭をスキャンする上限バイト数。生成マーカーはヘッダコメントに書かれる
/// ことがほとんどなので、先頭数 KB だけ読めば十分。
const SCAN_BYTES: usize = 4096;

/// Marker detection is deliberately limited to the header. Generated-file
/// declarations conventionally live there, while prose deeper in a file is much
/// more likely to describe generated code rather than declare the file generated.
const MAX_MARKER_LINES: usize = 40;

/// `path` のファイル先頭に自動生成マーカーが含まれるかを判定する。
/// 読み込みエラーや非 UTF-8 バイナリは保守的に `false` (生成物ではない) を返す。
pub fn is_auto_generated(path: &Path) -> bool {
    let Ok(mut f) = std::fs::File::open(path) else {
        return false;
    };
    let mut buf = vec![0u8; SCAN_BYTES];
    let n = match f.read(&mut buf) {
        Ok(n) => n,
        Err(_) => return false,
    };
    buf.truncate(n);
    head_declares_generated(&buf)
}

/// Return true only for a generated-file declaration in a header comment.
///
/// This intentionally prefers false negatives over false positives: excluding a
/// real source file silently removes it from every directory-wide query. The
/// caller can still include an unrecognised generated file, whereas a false
/// positive used to be indistinguishable from an identifier having no matches.
pub(crate) fn head_declares_generated(head: &[u8]) -> bool {
    String::from_utf8_lossy(head)
        .lines()
        .take(MAX_MARKER_LINES)
        .any(line_declares_generated)
}

fn line_declares_generated(raw: &str) -> bool {
    let line = raw.trim_start_matches([' ', '\t']);
    if line.starts_with("#!") {
        return false;
    }
    let Some(body) = strip_comment_prefix(line) else {
        return false;
    };
    let body = body
        .trim_start_matches([' ', '\t'])
        .strip_prefix('*')
        .unwrap_or(body.trim_start_matches([' ', '\t']))
        .trim_start_matches([' ', '\t'])
        .to_ascii_lowercase();
    marker_phrase_at_start(&body)
}

fn strip_comment_prefix(line: &str) -> Option<&str> {
    ["///", "//!", "//", "<!--", "/*", "#", "--", ";", "%", "*"]
        .into_iter()
        .find_map(|prefix| line.strip_prefix(prefix))
}

fn marker_phrase_at_start(body: &str) -> bool {
    if body.starts_with("<auto-generated>")
        || starts_with_word(body, "@generated")
        || starts_with_word(body, "code generated by")
        || starts_with_word(body, "generated by")
    {
        return true;
    }

    if declaration_phrase(body, "automatically generated")
        || declaration_phrase(body, "auto-generated")
        || declaration_phrase(body, "auto generated")
        || declaration_phrase(body, "autogenerated")
    {
        return true;
    }

    if let Some(rest) = body.strip_prefix("do not edit") {
        let rest = rest.trim_start_matches([' ', '\t']);
        return rest.is_empty()
            || rest.starts_with("this file")
            || rest.starts_with(['.', ',', ';', ':', '!', '-']);
    }

    let linked = [
        "this file",
        "this code",
        "this module",
        "this class",
        "this source",
        "this document",
        "this header",
        "file",
        "module",
        "code",
        "source",
    ]
    .into_iter()
    .find_map(|subject| strip_word_prefix(body, subject));

    let rest = linked
        .and_then(strip_linking_verb)
        .or_else(|| strip_linking_verb(body));
    rest.is_some_and(|rest| {
        declaration_phrase(rest, "generated")
            || declaration_phrase(rest, "automatically generated")
            || declaration_phrase(rest, "auto-generated")
            || declaration_phrase(rest, "auto generated")
            || declaration_phrase(rest, "autogenerated")
    })
}

fn strip_word_prefix<'a>(text: &'a str, prefix: &str) -> Option<&'a str> {
    let rest = text.strip_prefix(prefix)?;
    (rest.is_empty()
        || rest
            .as_bytes()
            .first()
            .is_some_and(|b| !b.is_ascii_alphanumeric() && *b != b'_'))
    .then_some(rest.trim_start_matches([' ', '\t']))
}

fn strip_linking_verb(text: &str) -> Option<&str> {
    [
        "has been",
        "have been",
        "will be",
        "is",
        "was",
        "were",
        "are",
    ]
    .into_iter()
    .find_map(|verb| strip_word_prefix(text.trim_start_matches([' ', '\t']), verb))
}

fn declaration_phrase(text: &str, phrase: &str) -> bool {
    let Some(rest) = strip_word_prefix(text, phrase) else {
        return false;
    };
    rest.is_empty()
        || rest.starts_with("by ")
        || rest.starts_with("from ")
        || rest.starts_with("using ")
        || rest.starts_with("file")
        || rest.starts_with("code")
        || rest.starts_with("source")
        || rest.starts_with("do not edit")
        || rest.starts_with(['.', ',', ';', ':', '!', '-'])
}

fn starts_with_word(text: &str, phrase: &str) -> bool {
    strip_word_prefix(text, phrase).is_some()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_tmp(name: &str, content: &str) -> std::path::PathBuf {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join(name);
        let mut f = std::fs::File::create(&path).expect("create");
        f.write_all(content.as_bytes()).expect("write");
        // tempdir は drop されるとパスが消えるので持続させる
        std::mem::forget(dir);
        path
    }

    #[test]
    fn detects_tree_sitter_parser_c() {
        let path = write_tmp(
            "parser.c",
            "/* Automatically generated by tree-sitter. */\nint main() {}\n",
        );
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn detects_protoc_go() {
        let path = write_tmp(
            "foo.pb.go",
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n",
        );
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn detects_at_generated_annotation() {
        let path = write_tmp("x.rs", "// @generated\nfn main() {}\n");
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn detects_csharp_auto_generated_header() {
        let path = write_tmp("x.cs", "// <auto-generated>\nclass Generated {}\n");
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn detects_comment_only_do_not_edit_marker() {
        let path = write_tmp("x.rb", "# DO NOT EDIT THIS FILE\ndef main; end\n");
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn rejects_generated_prose_in_comment() {
        let path = write_tmp(
            "x.rb",
            "# Detects double disable comments.\n# automatically generated comments must be regenerated.\ndef main; end\n",
        );
        assert!(!is_auto_generated(&path));
    }

    #[test]
    fn rejects_marker_text_in_string_literal() {
        let path = write_tmp("x.rb", "X = \"DO NOT EDIT\"\ndef main; end\n");
        assert!(!is_auto_generated(&path));
    }

    #[test]
    fn detects_subject_and_linking_verb_form() {
        let path = write_tmp("x.py", "# This file is automatically generated by a tool\n");
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn rejects_generated_word_inside_larger_identifier() {
        let path = write_tmp("x.py", "# autogeneratedness is discussed here\n");
        assert!(!is_auto_generated(&path));
    }

    #[test]
    fn rejects_normal_code() {
        let path = write_tmp(
            "normal.rs",
            "// Regular source file. Edit freely.\nfn main() {}\n",
        );
        assert!(!is_auto_generated(&path));
    }

    #[test]
    fn rejects_missing_file() {
        let path = std::path::PathBuf::from("/nonexistent/path/to/file.rs");
        assert!(!is_auto_generated(&path));
    }

    #[test]
    fn handles_non_utf8_binary() {
        // 無効な UTF-8 シーケンスが含まれていても false を返す (パニックしない)
        let path = write_tmp("bin.dat", "");
        std::fs::write(&path, [0xff, 0xfe, 0xfd, 0xfc]).expect("write");
        assert!(!is_auto_generated(&path));
    }
}
