//! コード生成ツールによる「自動生成ファイル」のマーカー検出。
//! `.gitattributes` の `linguist-generated` と独立に、ファイル先頭のコメントで
//! 生成物を宣言しているパターン (tree-sitter の `parser.c`、`protoc` の
//! `_pb.go` など) を捉える。dead-code / API 変更検出のノイズ抑制に使う。

use std::io::Read;
use std::path::Path;

/// ファイル先頭をスキャンする上限バイト数。生成マーカーはヘッダコメントに書かれる
/// ことがほとんどなので、先頭数 KB だけ読めば十分。
const SCAN_BYTES: usize = 4096;

/// 生成ファイルを示すマーカー (大文字小文字を区別せず比較)。
/// 「generated」系の語を含むものに限定し、「do not edit」単独のような弱いシグナルは
/// 除外する (通常コードのコメントで偶然マッチする恐れがあるため)。
const MARKERS: &[&str] = &[
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "@generated",
    "generated by",
    "this file was generated",
    "code generated by",
    "file is generated",
];

/// `path` のファイル先頭に自動生成マーカーが含まれるかを判定する。
/// 読み込みエラーや非 UTF-8 バイナリは保守的に `false` (生成物ではない) を返す。
pub fn is_auto_generated(path: &Path) -> bool {
    let Ok(mut f) = std::fs::File::open(path) else {
        return false;
    };
    let mut buf = vec![0u8; SCAN_BYTES];
    let n = match f.read(&mut buf) {
        Ok(n) => n,
        Err(_) => return false,
    };
    buf.truncate(n);
    let Ok(header) = std::str::from_utf8(&buf) else {
        return false;
    };
    let lower = header.to_ascii_lowercase();
    MARKERS.iter().any(|m| lower.contains(m))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_tmp(name: &str, content: &str) -> std::path::PathBuf {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join(name);
        let mut f = std::fs::File::create(&path).expect("create");
        f.write_all(content.as_bytes()).expect("write");
        // tempdir は drop されるとパスが消えるので持続させる
        std::mem::forget(dir);
        path
    }

    #[test]
    fn detects_tree_sitter_parser_c() {
        let path = write_tmp(
            "parser.c",
            "/* Automatically generated by tree-sitter. */\nint main() {}\n",
        );
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn detects_protoc_go() {
        let path = write_tmp(
            "foo.pb.go",
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n",
        );
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn detects_at_generated_annotation() {
        let path = write_tmp("x.rs", "// @generated\nfn main() {}\n");
        assert!(is_auto_generated(&path));
    }

    #[test]
    fn rejects_normal_code() {
        let path = write_tmp(
            "normal.rs",
            "// Regular source file. Edit freely.\nfn main() {}\n",
        );
        assert!(!is_auto_generated(&path));
    }

    #[test]
    fn rejects_missing_file() {
        let path = std::path::PathBuf::from("/nonexistent/path/to/file.rs");
        assert!(!is_auto_generated(&path));
    }

    #[test]
    fn handles_non_utf8_binary() {
        // 無効な UTF-8 シーケンスが含まれていても false を返す (パニックしない)
        let path = write_tmp("bin.dat", "");
        std::fs::write(&path, [0xff, 0xfe, 0xfd, 0xfc]).expect("write");
        assert!(!is_auto_generated(&path));
    }
}
